### ISSUE TITLE
Request for Support of "Response Format" Feature in OpenAI Assistant API

### ISSUE THREAD

**Issue by imzakria** [skyscrapr/terraform-provider-openai#100]
Hi, I greatly appreciate your work on the OpenAI Terraform provider.

Recently, OpenAI released a new feature called "Structured Outputs" in their API, which includes a "Response Format" option for generating valid JSON outputs. You can find a detailed explanation at the following link:

[Introducing Structured Outputs in the API](https://openai.com/index/introducing-structured-outputs-in-the-api/)

It would be fantastic if you could add support for the Response Format feature in the Terraform provider for the Assistant API.

Thank you in advance.

**Comment by skyscrapr** [comment]
Thanks for raising the issue. I'll have a look at this over the next day or so and see how hard this is to implement.

**Comment by skyscrapr** [comment]
@imzakria this looks pretty simple to implement. Let me take a closer look at this today. I think I can get this done over the weekend.

**Comment by imzakria** [comment]
Great!

**Comment by skyscrapr** [comment]
@imzakria give this a try and let me know if this works for you. Cheers

**Comment by imzakria** [comment]
Really appreciated! Thank you.
