### ISSUE TITLE
Project & API Key Creation?

### ISSUE THREAD

**Issue by hongkongkiwi** [skyscrapr/terraform-provider-openai#103]
Great plugin! 

Is it possible to add the project & api key functionality that is provided here?
https://github.com/jianyuan/terraform-provider-openai

**Comment by skyscrapr** [comment]
I can look at doing this over the weekend.

**Comment by skyscrapr** [comment]
@hongkongkiwi  I've added project support to the provider. This is merged to main but I have not yet released this in a tagged version.

Will look at API keys tomorrow. I don't think that sample you provided has implemented that correctly though. You cannot create and managed Project API Keys using the API. However you can manage Project Service Accounts. 

I think that resource will be `openai_project_service_account`. Any thoughts? Does this fit your use case? Or do you need to manage Users as well?

**Comment by skyscrapr** [comment]
I have also added support for `project_service_account` resource. Hopefully this resolves your use case.
