### ISSUE TITLE
Assistant with files

### ISSUE THREAD

**Issue by svperfecta** [skyscrapr/terraform-provider-openai#106]
Silly question, but is there an example somewhere of creating an assistant, and providing it with a bunch of files to work with?  Maybe a full example that shows changing temperature, etc.?   Is there a way to create a vector store?

**Comment by skyscrapr** [comment]
Hi there, 

I updated the examples with more complex sample that hopefully answers your question:

See here: [assistant example](https://registry.terraform.io/providers/skyscrapr/openai/latest/docs/resources/assistant)

Please re-open if you think this needs more.
