### ISSUE TITLE
Naming project service account API keys isn't possible

### ISSUE THREAD

**Issue by christophersjchow** [skyscrapr/terraform-provider-openai#112]
When I try to create a resource like this:

```tf
resource "openai_project_service_account" "example" {
  project_id = openai_project.example-project.id
  name = "Project Name"
  api_key {
    name = "Key name"
  }
}
```

I get the following
```
Blocks of type "api_key" are not expected here. Did you mean to define argument "api_key"? If so, use the equals sign to assign it a value.
```

The docs indicate this is a block is that incorrect?

**Comment by skyscrapr** [comment]
Let me double check.  I'll add an example to clear it up.

**Comment by skyscrapr** [comment]
Ok quick check suggests api_key is computed only. Ie. Should not be set by caller. You should just remove the api_key attribute. It's returned in the creation. 
I'll update the schema to reflect and this will update the docs.

**Comment by skyscrapr** [comment]
it's not possible to name the key using the api currently. This is not possible via the UI either.
