### ISSUE TITLE
Project service account secrets are null after initial apply

### ISSUE THREAD

**Issue by christophersjchow** [skyscrapr/terraform-provider-openai#113]
I have a use case where we would like to store the service account secret in a secrets manager. The apply initially to create the secret works fine but subsequent applies fail as the `api_key` attributes are no longer available against the `openai_project_service_account` resource.

Should this data be available in the state? I understand that Terraform is still working on how to handle sensitive values https://github.com/hashicorp/terraform/issues/516 but until that lands I think its reasonable to store the secret in the statefile.

**Comment by skyscrapr** [comment]
I'll look into it. 
You definitely have it at creation time. So maybe there is a bug in my "refresh" code. 

Give me a couple of days

**Comment by skyscrapr** [comment]
this should be resolve in v1.7.1
