### ISSUE TITLE
Error updating assistant in place

### ISSUE THREAD

**Issue by nathan-gilbert** [skyscrapr/terraform-provider-openai#73]
Hi, I tried updating an assistant in place by adding more tools to the tools list and received:

```
│ Error: Provider produced inconsistent result after apply
│
│ When applying changes to openai_assistant.test, provider "provider[\"registry.terraform.io/skyscrapr/openai\"]" produced an unexpected new value: .tools: element 1 has vanished.
│
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

Maybe this is a limitation of the API?

**Comment by skyscrapr** [comment]
Thanks for raising the issue. I'll take a look at this bit later today.

**Comment by skyscrapr** [comment]
@nathan-gilbert looks like there is support for updating assistants in the API. I can look at adding this support. Give me a day or two to resolve.

**Comment by nathan-gilbert** [comment]
@skyscrapr Thank you for the fast response! I'm really enjoying this provider, it makes it easy to define assistants in code for sanely iterating over them.

**Comment by skyscrapr** [comment]
Good use case. 👍

**Comment by skyscrapr** [comment]
@nathan-gilbert  Assistant resource has been updated to support the new attrbutes: 

- tool_resources
- temperature
- top_p

Updating an assistant is now also supported.

Tests and Documentation have been updated.

A new version of the provider has been released with this functionality v1.2.1.
You will need to update this provider in your workspaces. For command line you can do this via `terraform init -u`

I'm closing the issue. But feel free to re-open if there are still issues.


Thanks for raising the issue.

**Comment by nathan-gilbert** [comment]
@skyscrapr Thanks so much! Any venmo or equiv where I could send you a tip!

**Comment by skyscrapr** [comment]
@nathan-gilbert no worries at all. Check this works for you first :-) 

And if you really feel you must then I added a [buy me a coffee link ](https://www.buymeacoffee.com/skyscrapr)to the README.

cheers
