### ISSUE TITLE
Error Creating Assistant

### ISSUE THREAD

**Issue by Perdiga** [skyscrapr/terraform-provider-openai#90]
Hi I am trying the version 1.4.0 and I am getting this error when creating an assistant. The assistant is being create on Open AI

> │ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to openai_assistant.feedback-assistant, provider
│ "provider[\"registry.terraform.io/skyscrapr/openai\"]" produced an
│ unexpected new value: .tools: was null, but now
│ cty.ListValEmpty(cty.Object(map[string]cty.Type{"function":cty.Object(map[string]cty.Type{"description":cty.String,
│ "name":cty.String, "parameters":cty.String}), "type":cty.String})).
│ 
│ This is a bug in the provider, which should be reported in the provider's
│ own issue tracker.

Thanks

**Comment by skyscrapr** [comment]
sorry I broke it. I've added a number of tests to hopefully fix all the different tool and tool_resrouces use cases.

**Comment by skyscrapr** [comment]
just released 1.4.1 with test passing. 

Run go test -v -cover ./openai/
=== RUN   TestAccAssistantResource_tool_simple
--- PASS: TestAccAssistantResource_tool_simple (1.81s)
=== RUN   TestAccAssistantResource_tool_code_interpreter
--- PASS: TestAccAssistantResource_tool_code_interpreter (3.40s)
=== RUN   TestAccAssistantResource_tool_function
--- PASS: TestAccAssistantResource_tool_function (1.71s)
=== RUN   TestAccAssistantResource_file_search
--- PASS: TestAccAssistantResource_file_search (6.14s)
=== RUN   TestAccAssistantResource_complex
--- PASS: TestAccAssistantResource_complex (11.61s)
=== RUN   TestAccFileDataSource
--- PASS: TestAccFileDataSource (1.35s)
=== RUN   TestAccFileResource
--- PASS: TestAccFileResource (1.63s)
=== RUN   TestAccFilesDataSource
--- PASS: TestAccFilesDataSource (2.07s)
=== RUN   TestAccFineTuneDataSource
    provider_test.go:28: env var TF_ACC_OPENAI not set. Skipping acceptance test due to cost or time
--- SKIP: TestAccFineTuneDataSource (0.00s)
=== RUN   TestAccFineTuningJobResource
    provider_test.go:28: env var TF_ACC_OPENAI not set. Skipping acceptance test due to cost or time
--- SKIP: TestAccFineTuningJobResource (0.00s)
=== RUN   TestAccFineTuningJobsDataSource
--- PASS: TestAccFineTuningJobsDataSource (0.90s)
=== RUN   TestAccModelDataSource
--- PASS: TestAccModelDataSource (1.20s)
=== RUN   TestAccModelsDataSource
--- PASS: TestAccModelsDataSource (0.87s)
=== RUN   TestAccVectorStoreResource
--- PASS: TestAccVectorStoreResource (3.06s)
PASS
coverage: 58.9% of statements
ok  	github.com/skyscrapr/terraform-provider-openai/openai	35.765s	coverage: 58.9% of statements

please retest with latest version
